export const UNIVERSITY_SEED = [
  {
    name_zh: "西南大学",
    name_en: "Southwest University",
    slug: "southwest-university",
    city: "Chongqing",
    province: "Chongqing",
    department: "国际学生招生办",
    emails: ["admission@swu.edu.cn", "fstudent@swu.edu.cn"],
    phone: "68366001 / 68367823",
    website: "https://gjxy.swu.edu.cn/index.htm",
    last_contact_at: "2026-08-17",
    reply_status: "replied",
  },
  {
    name_zh: "上海大学",
    name_en: "Shanghai University",
    slug: "shanghai-university",
    city: "Shanghai",
    province: "Shanghai",
    department: "交换生/汉语项目",
    emails: ["apply4@oa.shu.edu.cn", "apply6@oa.shu.edu.cn"],
    phone: "86 21 66136615",
    website: "https://apply.shu.edu.cn/application/index?language=zh",
    last_contact_at: "2026-08-17",
    last_contact_note: "休假至9.5",
  },
  {
    name_zh: "中南大学",
    name_en: "Central South University",
    slug: "central-south-university",
    city: "Changsha",
    province: "Hunan",
    department: "中南大学国际教育学院国际学生招生办公室",
    emails: ["admissions@csu.edu.cn"],
    phone: "86 731 88836410",
    website: "https://intl.csu.edu.cn/zwb/lhlx.htm",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "广东外语外贸大学",
    name_en: "Guangdong University of Foreign Studies",
    slug: "gdufs",
    city: "Guangzhou",
    province: "Guangdong",
    department: "留学生教育学院",
    emails: ["iie@gdufs.edu.cn"],
    phone: "86 20 36207141",
    website: "http://iie.gdufs.edu.cn",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "中山大学",
    name_en: "Sun Yat-sen University",
    slug: "sun-yat-sen-university",
    city: "Guangzhou",
    province: "Guangdong",
    department: "外国留学生办公室",
    emails: ["admissions@mail.sysu.edu.cn"],
    phone: "86 20 84110819",
    website: "https://iso.sysu.edu.cn/cn/index.htm",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "厦门大学",
    name_en: "Xiamen University",
    slug: "xiamen-university",
    city: "Xiamen",
    province: "Fujian",
    department: "国际学生招生办",
    emails: ["admissions@xmu.edu.cn"],
    phone: "86 (0) 592 2184792",
    website: "https://admissions.xmu.edu.cn/cn/index.htm",
    last_contact_at: "2026-08-17",
    last_contact_note: "休假至9.3",
  },
  {
    name_zh: "北京语言大学",
    name_en: "Beijing Language and Culture University",
    slug: "blcu",
    city: "Beijing",
    province: "Beijing",
    department: "国际学生处",
    emails: ["cooperationcn@blcu.edu.cn"],
    phone: "0086-10-82303951 / 82303086 / 60303086",
    website: "https://admission.blcu.edu.cn/main.htm",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "燕山大学",
    name_en: "Yanshan University",
    slug: "yanshan-university",
    city: "Qinhuangdao",
    province: "Hebei",
    department: "国际教育学院",
    emails: ["study@ysu.edu.cn"],
    phone: "86 335-809-5518",
    website: "https://admission.ysu.edu.cn/",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "成都理工大学",
    name_en: "Chengdu University of Technology",
    slug: "chengdu-university-of-technology",
    city: "Chengdu",
    province: "Sichuan",
    department: "国际教育学院",
    emails: ["oshc@cdut.edu.cn"],
    phone: "0086-28-84078430",
    website: "https://cie.cdut.edu.cn/",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "华中科技大学",
    name_en: "Huazhong University of Science and Technology",
    slug: "hust",
    city: "Wuhan",
    province: "Hubei",
    department: "国际教育学院",
    emails: ["vivianyan@hust.edu.cn"],
    website: "https://iso.hust.edu.cn/Contact_Us/Admission___Cooperation_Office.htm",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "重庆大学",
    name_en: "Chongqing University",
    slug: "chongqing-university",
    city: "Chongqing",
    province: "Chongqing",
    department: "国际交流与合作处",
    emails: ["admissions@cqu.edu.cn"],
    phone: "0086-23-65111001",
    website: "https://study.cqu.edu.cn/index.htm",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "复旦大学",
    name_en: "Fudan University",
    slug: "fudan-university",
    city: "Shanghai",
    province: "Shanghai",
    department: "外国留学生工作处",
    emails: ["isoadmission@fudan.edu.cn"],
    phone: "(86)-(21)-65642250 / 65642258 / 65641231",
    website: "https://iso.fudan.edu.cn/",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "浙江大学",
    name_en: "Zhejiang University",
    slug: "zhejiang-university",
    city: "Hangzhou",
    province: "Zhejiang",
    department: "国际教育学院",
    emails: ["admission5@zju.edu.cn", "admissionmaster@zju.edu.cn"],
    phone: "+86 571 87951456 / +86 571 87951718",
    website: "http://iczu.zju.edu.cn/admissions/",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "昆明理工大学",
    name_en: "Kunming University of Science and Technology",
    slug: "kust",
    city: "Kunming",
    province: "Yunnan",
    department: "留学生招生办",
    emails: [],
    phone: "65939156",
    website: "https://gjxy.kust.edu.cn/index.htm",
  },
  {
    name_zh: "西安外国语大学",
    name_en: "Xi'an International Studies University",
    slug: "xisu",
    city: "Xi'an",
    province: "Shaanxi",
    department: "国际学生办公室",
    emails: ["admission@xisu.edu.cn"],
    phone: "86-29-85319321",
    website: "http://six.xisu.edu.cn/gywm/lxwm.htm",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "四川外国语大学",
    name_en: "Sichuan International Studies University",
    slug: "sisu",
    city: "Chongqing",
    province: "Chongqing",
    department: "国际合作与交流处（港澳台办公室）",
    emails: ["studyinsisu@sisu.edu.cn", "studyinsisu-sis@sisu.edu.cn"],
    phone: "0086-23-65380021（学历生） / 0086-23-65381037（进修生）",
    website: "https://studyinsisu.sisu.edu.cn/",
    last_contact_at: "2026-08-17",
    reply_status: "no_reply",
    notes: "邮件被ban",
  },
  {
    name_zh: "重庆师范大学",
    name_en: "Chongqing Normal University",
    slug: "chongqing-normal-university",
    city: "Chongqing",
    province: "Chongqing",
    department: "国际合作与交流处（港澳台办公室）",
    emails: ["interoff@cqnu.edu.cn", "cqnuws@foxmail.com"],
    phone: "0086-23-65362300 / 0086-23-65918980",
    website: "https://international.cqnu.edu.cn/lxzs/zsxx.htm",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "重庆工商大学",
    name_en: "Chongqing Technology and Business University",
    slug: "ctbu",
    city: "Chongqing",
    province: "Chongqing",
    department: "国际合作与交流处（港澳台办公室）留学生院",
    emails: ["wshch@ctbu.edu.cn"],
    phone: "86-23-62769399",
    website: "https://interoffice2014.ctbu.edu.cn/lxgsd.htm",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "重庆理工大学",
    name_en: "Chongqing University of Technology",
    slug: "cqut",
    city: "Chongqing",
    province: "Chongqing",
    department: "两江国际学院",
    emails: ["lic@vip.cqut.edu.cn"],
    phone: "023-62563611",
    website: "https://lic.cqut.edu.cn/xygk/xyjj.htm",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "重庆交通大学",
    name_en: "Chongqing Jiaotong University",
    slug: "cqjtu",
    city: "Chongqing",
    province: "Chongqing",
    department: "国际合作交流处",
    emails: ["waiban@vip.163.com"],
    phone: "023-62652602",
    website: "https://oice.cqjtu.edu.cn/index.htm",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "重庆科技大学",
    name_en: "Chongqing University of Science and Technology",
    slug: "cqust",
    city: "Chongqing",
    province: "Chongqing",
    department: "国际合作交流处",
    emails: ["internationalcollege@cqust.edu.cn"],
    phone: "023-65022514",
    website: "https://wsc.cqust.edu.cn/index.htm",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "四川美术学院",
    name_en: "Sichuan Fine Arts Institute",
    slug: "scfai",
    city: "Chongqing",
    province: "Chongqing",
    department: "国际交流合作处",
    emails: ["guojichu@scfai.edu.cn"],
    phone: "86-23-65920818",
    website: "https://www.scfai.edu.cn",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "长江师范学院",
    name_en: "Yangtze Normal University",
    slug: "yangtze-normal-university",
    city: "Chongqing",
    province: "Chongqing",
    department: "国际学院",
    emails: ["international@yznu.edu.cn"],
    phone: "023-72791119",
    website: "https://guojjl.yznu.edu.cn/83/list.htm",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "四川大学",
    name_en: "Sichuan University",
    slug: "sichuan-university",
    city: "Chengdu",
    province: "Sichuan",
    department: "国际合作交流处",
    emails: ["bioluo@scu.edu.cn", "studychinese_scu@163.com"],
    phone: "86-28-85407199 / 85405773",
    website: "https://global.scu.edu.cn/oso/",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "电子科技大学",
    name_en: "University of Electronic Science and Technology of China",
    slug: "uestc",
    city: "Chengdu",
    province: "Sichuan",
    department: "留学生招生教务管理办公室",
    emails: ["international@uestc.edu.cn"],
    phone: "61831638 / 61831730 / 61831089",
    website: "https://www.oice.uestc.edu.cn/",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "西南交通大学",
    name_en: "Southwest Jiaotong University",
    slug: "swjtu",
    city: "Chengdu",
    province: "Sichuan",
    department: "国际教育学院",
    emails: ["iso@swjtu.edu.cn"],
    phone: "(+86-28) 66366343 / 66366902",
    website: "https://sie.swjtu.edu.cn/",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "西南财经大学",
    name_en: "Southwestern University of Finance and Economics",
    slug: "swufe",
    city: "Chengdu",
    province: "Sichuan",
    department: "国际教育学院招生办公室",
    emails: ["admission@swufe.edu.cn"],
    phone: "86(28)-8735 5437",
    website: "https://international.swufe.edu.cn/index.htm",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "四川师范大学",
    name_en: "Sichuan Normal University",
    slug: "sichuan-normal-university",
    city: "Chengdu",
    province: "Sichuan",
    department: "国际中文教育学院",
    emails: ["guoxxiaolei@sicnu.edu.cn"],
    phone: "0086-28-84767720 / 0086-28-84761093",
    website: "https://lxs.sicnu.edu.cn/",
    notes: "仅接受 HSK4 及以上，专业中国国际教育",
    min_hsk_level: 4,
  },
  {
    name_zh: "西南民族大学",
    name_en: "Southwest Minzu University",
    slug: "southwest-minzu-university",
    city: "Chengdu",
    province: "Sichuan",
    department: "国际教育学院办公室",
    emails: ["Internationalstudents@swun.edu.cn"],
    phone: "0086-28-85522042",
    website: "https://gjc.swun.edu.cn/index.htm",
    last_contact_at: "2026-08-17",
  },
  {
    name_zh: "重庆邮电大学",
    name_en: "Chongqing University of Posts and Telecommunications",
    slug: "cqupt",
    city: "Chongqing",
    province: "Chongqing",
    department: "国际合作与交流处",
    emails: ["admission@cqupt.edu.cn"],
    phone: "(+86-23)-62487785",
    website: "https://international.cqupt.edu.cn/index.htm",
    last_contact_at: "2026-08-17",
  },
];

export function toUniversityInsert(row) {
  return {
    name_zh: row.name_zh,
    name_en: row.name_en || null,
    name_fr: row.name_fr || null,
    slug: row.slug,
    city: row.city || null,
    province: row.province || null,
    country: "Chine",
    department: row.department || null,
    emails: row.emails || [],
    phone: row.phone || null,
    wechat: row.wechat || null,
    website: row.website || null,
    last_contact_at: row.last_contact_at || null,
    last_contact_note: row.last_contact_note || null,
    reply_status: row.reply_status || null,
    notes: row.notes || null,
    is_partner: true,
    is_active: true,
    majors: row.majors || [],
    required_documents: row.required_documents || [],
    scholarship_amount: row.scholarship_amount || null,
    scholarship_min: row.scholarship_min ?? null,
    scholarship_max: row.scholarship_max ?? null,
    min_hsk_level: row.min_hsk_level ?? null,
    language_requirements: row.language_requirements || null,
    tuition_min: row.tuition_min ?? null,
    tuition_max: row.tuition_max ?? null,
    application_deadline: row.application_deadline || null,
  };
}